accounts/urls.py
from  django.urls import path , include
from economic import settings
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('my_account/', views.my_account, name='my_account'),
   # path('order_details/', views.orderdetails, name='order_details'),
   # path('order_info/', views.orderinfo, name='order_info'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password_change/', views.change_password, name='password_change'),
    path('password_change_done/', views.password_change_done, name='password_change_done')
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.show_cart, name='show_cart')
]

catalog/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='catalog_home'),
    path('category/<category_slug>/', views.show_category, name='catalog_category'),
    path('product/<product_slug>', views.show_product, name='catalog_product'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

economic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('preview/', include('preview.urls')),
    path('catalog/', include('catalog.urls')),
    path('cart/', include('cart.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/tags/cart_box.html
{% with cart_item_count as cart_count %}
<a href="{% url 'cart:show_cart' %} ">
    Shopping Cart
<br />
{{ cart_count }} Item{{ cart_count|pluralize }}
</a>
{% endwith %}

templates/tags/category_list.html
<h3>Categories</h3>
<ul id="categories">
{% with active_categories as cats %}
{% for c in cats %}
<li>
{% ifequal c.get_absolute_url request_path %}
{{ c.name }}<br />
{% else %}
<a href="{{ c.get_absolute_url }}" class="category">{{ c.name }}</a><br />
{% endifequal %}
</li>
{% endfor %}
{% endwith %}
</ul>

templates/tags/footer.html
<a href="{% url 'catalog:catalog_home' %}">Home</a>
{% with flatpage_list as pages %}
{% for page in pages %}
<a href="{{ page.url }}">{{ page.title }}</a>
{% endfor %}
{% endwith %}
<a href="{% url 'cart:show_cart' %}">Shopping Cart</a>

templates/tags/navigation.html
<ul>
<li><a href="{% url 'catalog:catalog_home' %}">Home</a></li>
<li><a href="/about/">About</a></li>
<li><a href="/privacy-policy/">Privacy</a></li>
<li><a href="/contact/">Contact</a></li>
<li><a href="{% url 'accounts:my_account' %}">My Account</a></li>
</ul>
<div class="fr">
<ul>
    <li>
        {% if user.is_authenticated %}
            <a href="{%  url 'accounts:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'accounts:register' %}">Sign Up</a>
            </li>
            <li>
            <a href="{% url 'accounts:login' %}">Login</a>
        {% endif %}
    </li>
</ul>
</div>
<div class="cb"></div>